# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtapp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 490, 131, 31))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_8.setAutoFillBackground(False)
        self.horizontalSlider_8.setMinimum(42)
        self.horizontalSlider_8.setMaximum(82)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_8)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_8.setMinimum(42)
        self.spinBox_8.setMaximum(82)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_16.addWidget(self.spinBox_8)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 440, 131, 31))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider_7.setAutoFillBackground(False)
        self.horizontalSlider_7.setMinimum(49)
        self.horizontalSlider_7.setMaximum(110)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalLayout_26.addWidget(self.horizontalSlider_7)
        self.spinBox_7 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_7.setMinimum(49)
        self.spinBox_7.setMaximum(110)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_26.addWidget(self.spinBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 380, 131, 31))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.layoutWidget_2)
        self.horizontalSlider_6.setAutoFillBackground(False)
        self.horizontalSlider_6.setMinimum(60)
        self.horizontalSlider_6.setMaximum(110)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalLayout_17.addWidget(self.horizontalSlider_6)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_6.setMinimum(60)
        self.spinBox_6.setMaximum(110)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_17.addWidget(self.spinBox_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 320, 131, 31))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.layoutWidget_3)
        self.horizontalSlider_5.setAutoFillBackground(False)
        self.horizontalSlider_5.setMinimum(40)
        self.horizontalSlider_5.setMaximum(109)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalLayout_18.addWidget(self.horizontalSlider_5)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_5.setMinimum(40)
        self.spinBox_5.setMaximum(109)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_18.addWidget(self.spinBox_5)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 260, 131, 31))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.layoutWidget_4)
        self.horizontalSlider_4.setAutoFillBackground(False)
        self.horizontalSlider_4.setMinimum(67)
        self.horizontalSlider_4.setMaximum(75)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_19.addWidget(self.horizontalSlider_4)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_4.setMinimum(67)
        self.spinBox_4.setMaximum(75)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_19.addWidget(self.spinBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(60, 110, 131, 31))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.layoutWidget_5)
        self.horizontalSlider_1.setAutoFillBackground(False)
        self.horizontalSlider_1.setMinimum(35)
        self.horizontalSlider_1.setMaximum(115)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalLayout_20.addWidget(self.horizontalSlider_1)
        self.spinBox_1 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_1.setMinimum(35)
        self.spinBox_1.setMaximum(115)
        self.spinBox_1.setObjectName("spinBox_1")
        self.horizontalLayout_20.addWidget(self.spinBox_1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 210, 131, 31))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget_6)
        self.horizontalSlider_3.setAutoFillBackground(False)
        self.horizontalSlider_3.setMinimum(40)
        self.horizontalSlider_3.setMaximum(83)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_21.addWidget(self.horizontalSlider_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_3.setMinimum(40)
        self.spinBox_3.setMaximum(83)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_21.addWidget(self.spinBox_3)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(290, 60, 131, 31))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget_7)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(35)
        self.horizontalSlider.setMaximum(115)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_27.addWidget(self.horizontalSlider)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox.setMinimum(35)
        self.spinBox.setMaximum(115)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_27.addWidget(self.spinBox)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 150, 131, 31))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_8.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget_8)
        self.horizontalSlider_2.setAutoFillBackground(False)
        self.horizontalSlider_2.setMinimum(45)
        self.horizontalSlider_2.setMaximum(101)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_22.addWidget(self.horizontalSlider_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinBox_2.setMinimum(45)
        self.spinBox_2.setMaximum(101)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_22.addWidget(self.spinBox_2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(390, 100, 131, 31))
        self.groupBox_10.setAutoFillBackground(True)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_9.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalSlider_9 = QtWidgets.QSlider(self.layoutWidget_9)
        self.horizontalSlider_9.setAutoFillBackground(False)
        self.horizontalSlider_9.setMinimum(35)
        self.horizontalSlider_9.setMaximum(115)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalLayout_23.addWidget(self.horizontalSlider_9)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_9.setMinimum(35)
        self.spinBox_9.setMaximum(115)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_23.addWidget(self.spinBox_9)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(460, 270, 131, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalSlider_12 = QtWidgets.QSlider(self.layoutWidget_10)
        self.horizontalSlider_12.setAutoFillBackground(False)
        self.horizontalSlider_12.setMinimum(67)
        self.horizontalSlider_12.setMaximum(75)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.horizontalLayout_24.addWidget(self.horizontalSlider_12)
        self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget_10)
        self.spinBox_12.setMinimum(67)
        self.spinBox_12.setMaximum(75)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_24.addWidget(self.spinBox_12)
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(440, 150, 131, 31))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget_11.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalSlider_10 = QtWidgets.QSlider(self.layoutWidget_11)
        self.horizontalSlider_10.setAutoFillBackground(False)
        self.horizontalSlider_10.setMinimum(45)
        self.horizontalSlider_10.setMaximum(101)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.horizontalLayout_25.addWidget(self.horizontalSlider_10)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_11)
        self.spinBox_10.setMinimum(45)
        self.spinBox_10.setMaximum(101)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_25.addWidget(self.spinBox_10)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(450, 320, 131, 31))
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_13)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.layoutWidget_12)
        self.horizontalSlider_13.setAutoFillBackground(False)
        self.horizontalSlider_13.setMinimum(40)
        self.horizontalSlider_13.setMaximum(109)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.horizontalLayout_28.addWidget(self.horizontalSlider_13)
        self.spinBox_13 = QtWidgets.QSpinBox(self.layoutWidget_12)
        self.spinBox_13.setMinimum(40)
        self.spinBox_13.setMaximum(109)
        self.spinBox_13.setObjectName("spinBox_13")
        self.horizontalLayout_28.addWidget(self.spinBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(460, 220, 131, 31))
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.layoutWidget_13 = QtWidgets.QWidget(self.groupBox_14)
        self.layoutWidget_13.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.layoutWidget_13)
        self.horizontalSlider_11.setAutoFillBackground(False)
        self.horizontalSlider_11.setMinimum(40)
        self.horizontalSlider_11.setMaximum(83)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.horizontalLayout_29.addWidget(self.horizontalSlider_11)
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_13)
        self.spinBox_11.setMinimum(40)
        self.spinBox_11.setMaximum(83)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_29.addWidget(self.spinBox_11)
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(420, 380, 131, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget_14.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.layoutWidget_14)
        self.horizontalSlider_14.setAutoFillBackground(False)
        self.horizontalSlider_14.setMinimum(60)
        self.horizontalSlider_14.setMaximum(110)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.horizontalLayout_30.addWidget(self.horizontalSlider_14)
        self.spinBox_14 = QtWidgets.QSpinBox(self.layoutWidget_14)
        self.spinBox_14.setMinimum(60)
        self.spinBox_14.setMaximum(110)
        self.spinBox_14.setObjectName("spinBox_14")
        self.horizontalLayout_30.addWidget(self.spinBox_14)
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(420, 490, 131, 31))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.layoutWidget_15 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_15.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalSlider_16 = QtWidgets.QSlider(self.layoutWidget_15)
        self.horizontalSlider_16.setAutoFillBackground(False)
        self.horizontalSlider_16.setMinimum(42)
        self.horizontalSlider_16.setMaximum(82)
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setObjectName("horizontalSlider_16")
        self.horizontalLayout_31.addWidget(self.horizontalSlider_16)
        self.spinBox_16 = QtWidgets.QSpinBox(self.layoutWidget_15)
        self.spinBox_16.setMinimum(42)
        self.spinBox_16.setMaximum(82)
        self.spinBox_16.setObjectName("spinBox_16")
        self.horizontalLayout_31.addWidget(self.spinBox_16)
        self.groupBox_17 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(420, 450, 131, 31))
        self.groupBox_17.setAutoFillBackground(True)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.layoutWidget_16 = QtWidgets.QWidget(self.groupBox_17)
        self.layoutWidget_16.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalSlider_15 = QtWidgets.QSlider(self.layoutWidget_16)
        self.horizontalSlider_15.setAutoFillBackground(False)
        self.horizontalSlider_15.setMinimum(49)
        self.horizontalSlider_15.setMaximum(110)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.horizontalLayout_32.addWidget(self.horizontalSlider_15)
        self.spinBox_15 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_15.setMinimum(49)
        self.spinBox_15.setMaximum(110)
        self.spinBox_15.setObjectName("spinBox_15")
        self.horizontalLayout_32.addWidget(self.spinBox_15)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 560, 71, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 599, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("_background.jpg"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(21, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(118, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(215, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(312, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(507, 13, 80, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label.raise_()
        self.textBrowser.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.groupBox_7.raise_()
        self.groupBox_8.raise_()
        self.groupBox_9.raise_()
        self.groupBox_10.raise_()
        self.groupBox_11.raise_()
        self.groupBox_12.raise_()
        self.groupBox_13.raise_()
        self.groupBox_14.raise_()
        self.groupBox_15.raise_()
        self.groupBox_16.raise_()
        self.groupBox_17.raise_()
        self.pushButton_7.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.spinBox_9.valueChanged['int'].connect(self.horizontalSlider_9.setValue)
        self.horizontalSlider_9.valueChanged['int'].connect(self.spinBox_9.setValue)
        self.horizontalSlider_10.valueChanged['int'].connect(self.spinBox_10.setValue)
        self.spinBox_10.valueChanged['int'].connect(self.horizontalSlider_10.setValue)
        self.horizontalSlider_11.valueChanged['int'].connect(self.spinBox_11.setValue)
        self.spinBox_11.valueChanged['int'].connect(self.horizontalSlider_11.setValue)
        self.horizontalSlider_12.valueChanged['int'].connect(self.spinBox_12.setValue)
        self.spinBox_12.valueChanged['int'].connect(self.horizontalSlider_12.setValue)
        self.horizontalSlider_13.valueChanged['int'].connect(self.spinBox_13.setValue)
        self.spinBox_13.valueChanged['int'].connect(self.horizontalSlider_13.setValue)
        self.horizontalSlider_14.valueChanged['int'].connect(self.spinBox_14.setValue)
        self.spinBox_14.valueChanged['int'].connect(self.horizontalSlider_14.setValue)
        self.horizontalSlider_15.valueChanged['int'].connect(self.spinBox_15.setValue)
        self.spinBox_15.valueChanged['int'].connect(self.horizontalSlider_15.setValue)
        self.horizontalSlider_16.valueChanged['int'].connect(self.spinBox_16.setValue)
        self.spinBox_16.valueChanged['int'].connect(self.horizontalSlider_16.setValue)
        self.horizontalSlider_1.valueChanged['int'].connect(self.spinBox_1.setValue)
        self.spinBox_1.valueChanged['int'].connect(self.horizontalSlider_1.setValue)
        self.horizontalSlider_2.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.horizontalSlider_2.setValue)
        self.horizontalSlider_3.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.horizontalSlider_3.setValue)
        self.horizontalSlider_4.valueChanged['int'].connect(self.spinBox_4.setValue)
        self.spinBox_4.valueChanged['int'].connect(self.horizontalSlider_4.setValue)
        self.horizontalSlider_5.valueChanged['int'].connect(self.spinBox_5.setValue)
        self.spinBox_5.valueChanged['int'].connect(self.horizontalSlider_5.setValue)
        self.horizontalSlider_6.valueChanged['int'].connect(self.spinBox_6.setValue)
        self.spinBox_6.valueChanged['int'].connect(self.horizontalSlider_6.setValue)
        self.horizontalSlider_7.valueChanged['int'].connect(self.spinBox_7.setValue)
        self.spinBox_7.valueChanged['int'].connect(self.horizontalSlider_7.setValue)
        self.horizontalSlider_8.valueChanged['int'].connect(self.spinBox_8.setValue)
        self.spinBox_8.valueChanged['int'].connect(self.horizontalSlider_8.setValue)
        self.pushButton_7.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.pushButton.setText(_translate("MainWindow", "紀錄目前位置"))
        self.pushButton_2.setText(_translate("MainWindow", "試播動作串"))
        self.pushButton_3.setText(_translate("MainWindow", "刪除動作串"))
        self.pushButton_4.setText(_translate("MainWindow", "儲存動作串"))
        self.pushButton_5.setText(_translate("MainWindow", "播放檔案"))
        self.pushButton_6.setText(_translate("MainWindow", "最佳位置"))

